### ISSUE TITLE
Invalid action 'get_database_entries'

### ISSUE THREAD

**Issue by FredericHamel** [hargoniX/keepassxc-proxy-client#8]
I was trying out keepassxc-proxy-client, this is awesome. But I cannot list entries in a database to allow choosing an entry in a fuzzy finder such as dmenu or fzf.

```
import keepassxc_proxy_client
import keepassxc_proxy_client.protocol

connection = keepassxc_proxy_client.protocol.Connection()
connection.connect()
connection.associate()

# The following method doesn't work
print(connection.get_database_entries())
```

The exception looks like this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...", line 178, in get_database_entries
    response = self.get_encrypted_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...", line 196, in get_encrypted_response
    raise ResponseUnsuccesfulException(raw_response)
keepassxc_proxy_client.protocol.ResponseUnsuccesfulException: {'action': 'get-database-entries', 'error': 'Incorrect action', 'errorCode': '12'}
```

**Comment by FredericHamel** [comment]
I looked inside "keepassxc" source code and notice that `get_database_entries` is not available in 2.7.5 and will be available in a future version.
